---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bytestash
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: bytestash
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bytestash
        namespace: ${releaseNamespace}
      version: 0.1.1
  interval: 1m0s
  install:
    createNamespace: true
    crds: CreateReplace
  targetNamespace: ${releaseNamespace}
  releaseName: bytestash
  valuesFrom:
    - kind: ConfigMap
      name: bytestash-0.1.1-defaults
    - kind: ConfigMap
      name: bytestash-overrides
      optional: true
