---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  annotations:
    metadata.weave.works/description: This is the source location for the Weave GitOps Dashboard's helm chart.
  name: ww-gitops
  namespace: ${releaseNamespace}
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/part-of: weave-gitops
spec:
  interval: 10m
  timeout: 1m
  type: oci
  url: oci://ghcr.io/weaveworks/charts
