---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-operator
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://grafana.github.io/helm-charts
