kind: Namespace
apiVersion: v1
metadata:
  name: milvus
---
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus
  namespace: milvus
spec:
  mode: standalone # Optional ("standalone", "cluster") default="standalone"
  components:
    image: milvusdb/milvus:v2.6.9
  dependencies: {} # Optional
  config: {} # Optional
