---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${releaseName}-${appVersion}-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |-
    image:
      repository: docker.io/milvusdb/milvus-operator
