---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weave-gitops-4.0.36-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    additionalArgs:
      - --route-prefix=/weave-gitops
    adminUser:
      create: true
      username: admin
      passwordHash: $2y$05$cZqELlSiL7mHz/jWch481OlZ1ZxrwUDFVpo7NItOP8M3KkBhzmTCS # The default password is nutanix/4u
    envVars:
      - name: WEAVE_GITOPS_FEATURE_TELEMETRY
        value: "false"
    ingress:
      enabled: true
      # annotations:
      #   traefik.ingress.kubernetes.io/router.middlewares: ${releaseNamespace}-redirect-to-sslip@kubernetescrd
      className: kommander-traefik
      hosts:
        - host: ""
          paths:
            - path: /weave-gitops
              pathType: Prefix
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weave-gitops-dashboard
  namespace: ${releaseNamespace}
  labels:
    kommander.d2iq.io/application: weave-gitops
data:
  dashboardLink: /weave-gitops
  docsLink: "https://docs.gitops.weaveworks.org/docs/intro-weave-gitops/"
  name: Weave GitOps
  version: 4.0.36
