---
apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-2.6.9-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    image:
      all:
        tag: v2.6.9
    cluster:
      enabled: false
    pulsarv3:
      enabled: false
    standalone:
      messageQueue: woodpecker
    woodpecker:
      enabled: true
    streaming:
      enabled: true
