apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnamicharts
  - hub.jupyter.org
  - weave-gitops
  - charts.gitlab.io
  - helm.openwebui.com
  - otwld.github.io
  - rocm.github.io
  - la-cc.github.io
  - jordan-dalby.github.io
  - helm.elastic.co
