apiVersion: v1
kind: Namespace
metadata:
  name: milvus
---
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus-standalone
  namespace: milvus
spec:
  mode: standalone # Optional ("standalone", "cluster") default="standalone"
  components:
    image: milvusdb/milvus:v2.6.10
  dependencies: {} # Optional
  config: {} # Optional
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: milvus-ingress
  namespace: milvus
spec:
  rules:
    - host: milvus.${ingressAddress}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: milvus-standalone-milvus
                port:
                  number: 9091
