---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-9.0.2-defaults
  namespace: gitlab
data:
  values.yaml: |
    ---
    global:
      edition: ce
      hosts:
        domain: ${ingressAddress}
      ingress:
        configureCertmanager: false
        class: kommander-traefik
        provider: traefik
    certmanager:
      install: false
    nginx-ingress:
      enabled: false
    gitlab-runner:
      install: false
    prometheus:
      install: false
    registry:
      enabled: false
    gitlab:
      gitlab-shell:
        minReplicas: 1
        maxReplicas: 1
      gitlab-exporter:
        enabled: false
      webservice:
        minReplicas: 1
        maxReplicas: 1
      kas:
        minReplicas: 1
        maxReplicas: 1
