---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: ${releaseNamespace}
  annotations:
    metadata.weave.works/description: This is the Weave GitOps Dashboard. It provides a simple way to get insights into your GitOps workloads.
spec:
  chart:
    spec:
      chart: weave-gitops
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: ${releaseNamespace}
  interval: 1m
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  releaseName: weave-gitops
  targetNamespace: ${releaseNamespace}
  valuesFrom:
    - kind: ConfigMap
      name: weave-gitops-4.0.36-defaults
    - kind: ConfigMap
      name: weave-gitops-overrides
      optional: true
