---
apiVersion: v1
kind: ConfigMap
metadata:
  name: infisical-0.147.0-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    infisical:
      image:
        repository: infisical/infisical
        tag: "v0.149.0"
        pullPolicy: IfNotPresent
