apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ${releaseName}-1.3.5-chart
  namespace: ${releaseNamespace}
spec:
  interval: 6h0m0s
  timeout: 1m
  url: https://zilliztech.github.io/milvus-operator/
  ref:
    tag: 1.3.5
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: milvus-operator
  namespace: ${releaseNamespace}
spec:
  chartRef:
    kind: HelmRepository
    name: ${releaseName}-1.3.5-chart
    namespace: ${releaseNamespace}
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 30
  interval: 15s
  targetNamespace: ${releaseNamespace}
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-1.3.5-config-defaults
